name: Backend Imaging Tests

on:
  pull_request:
    types: ['synchronize', 'opened', 'reopened']

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Apt-get Update
      run: sudo apt-get update

    - name: Pip Install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      env:
        USERID: ${{ secrets.USPS_USER_ID }}
      run: |
         python3 -m unittest
